# Site settings
title: Chestnuts
email: qiweiwei_hi@163.com
description: > # this means to ignore newlines until "baseurl:"
  It's never too late to get started.
baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 青葙
github_username:  ourchestnuts

# Build settings
markdown: kramdown
